name: "Bug Report"
description: "Report a bug in Spendly"
title: "[BUG]: "
body:
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug
      placeholder: "Explain the issue clearly"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: "1. Go to...\n2. Click...\n3. Crash"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
