name: "Feature Request"
description: "Propose a new feature or enhancement"
title: "[FEATURE]: "
body:
  - type: textarea
    id: idea
    attributes:
      label: Describe your idea
      placeholder: "What do you want to add?"
      required: true
